### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/nmtests#1]
Hi @kylebaron 

FYI, this is the repo that was used to generate `nlmixr2data::nmtest`, and is based on your `nmtests` repository.

I am opening this to share with Bob, because it identifies some bugs in NONMEM.

**Comment by kylebaron** [comment]
Thanks, @mattfidler. Yeah, sometimes it isn't easy to know if unexpected behavior is coming from NONMEM or mrgsolve / rxode2. Looking forward to following this and learning more about behavior of each.

**Comment by mattfidler** [comment]
In this case mrgsolve doesn't support yet.  Rxode2 supports in odes and NONMEM gives negative results which I believe are wrong.

**Comment by mattfidler** [comment]
I got a response that it was documented in the manual that what I was doing was unsupported.  Also FYI.
